name: divvy
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

# Check to see if supported packages have been upgraded
# https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.2.5+1
  firebase_analytics: ^1.1.0
  cloud_firestore: ^0.8.2+3
  firebase_auth: ^0.7.0
  google_sign_in: ^3.2.4
  rxdart: 0.21.0
  camera: ^0.4.0+3
  path_provider: ^0.5.0+1
  json_annotation: ^2.0.0
  http:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter:

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
          style: italic

    # - family: RobotoSlab
    #   fonts:
    #     - asset: assets/fonts/Roboto_Slab/RobotoSlab-Thin.ttf
    #       style: normal
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
